server:
  port: 9090

spring:
  application:
    name: aggrid-excel-data-writer
  datasource:
    url: jdbc:h2:tcp://localhost/~/agGridBook
    username: sa
    password: book
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


